theme: jekyll-theme-architect
title: CC-SoroOS
description: 
show_downloads: true

github:
  zip_url: https://github.com/lolBoi9696/CC-SoroOS/releases
  tar_gz_url: https://github.com/lolBoi9696/CC-SoroOS/releases
  another_url: https://github.com/lolBoi9696/CC-SoroOS/
