shell.run("pastebin get qBQzfk4k git.lua")
shell.run("git.lua lolBoi9696 CC-SoroOS / /OS master")
term.clear()
term.setCursorPos(1,1)
print("Restarting in 3 seconds")
sleep(1)
print("Restarting in 2 seconds")
sleep(1)
print("Restarting in 1 second")
sleep(1)
shell.run("reboot")